### ISSUE TITLE
100% of Failed: 200 OK @ 21.0 MB / sec

### ISSUE THREAD

**Issue by palpinter** [tomitrescak/meteor-uploads#145]
Hi,

I installed and configured server and jquery components followed stepy-by-step your readme.
I used bootstrap template. But after upload I got:

100% of Failed: 200 OK @ 21.0 MB / sec

I don't have a clue, why.

Thx
P.

**Comment by batjko** [comment]
Can you post some more details, like the full error stack if possible?

**Comment by meuhtrog** [comment]
Hi, i think i have the same issue : 100% of Failed: 0 error @ 8.99 MB / sec.
It's working fine on my localhost but not at all on my server (digitalOcean).

If i look at the console i can see i have these errors:
GET http://mysite/sockjs/info?cb=fgpzfrxeyv net::ERR_CONNECTION_RESET
POST http://mysite/upload net::ERR_CONNECTION_RESET
GET http://mysite/sockjs/info?cb=pe00pir_ns net::ERR_CONNECTION_REFUSED

So i guessed it's not working because of some security issues, but i have no clue how to solve it.
Do you have the same palpinter ?

**Comment by onbjerg** [comment]
I've had this issue as well. It is usually caused by the following problems:

1. The directories to not exist (make sure ``checkCreateDirectories`` is set to ``true`` in your options)
2. Your permissions are incorrect on your folder

Ensure that you have ownership (or your Meteor user does) of the uploads directory and that it has read/write permissions, e.g. 755 or if you're feeling like a dare-devil 777).

**Comment by tomitrescak** [comment]
Closing for now. Please reopen if necessary,

**Comment by jpmolinamatute** [comment]
I'm having the same problem. I don't get any error message or anything that can help me to debug this problem. I made sure to follow @onbjerg 's instructions

**Comment by meuhtrog** [comment]
One guy fixed this problem and said this : 	
"So the permissions where the problem but my uploads-folder already did have chmod 755. What the problem was is that the folder was owned by the root user while the user trying to upload was the user made by meteor. So I didn't change the chmod but the owner of the folder with chown. The problem probably occurred because I deployed the uploads-folder to the server and didn't let the package create the folder."
