### ISSUE TITLE
formdata in getDirectory is not actualized

### ISSUE THREAD

**Issue by glyphing** [tomitrescak/meteor-uploads#146]
In the client I deliver a formData containing a token:
```handlebar
 {{> upload_bootstrap fileTypes='.csv' multiple=false callbacks=uploadCallbacks formData=getFormData}}
```

This helper should be reactive because of Meteor.user():
```coffee 
Template.manageUsersImport.helpers
  getFormData: ->
    Template.instance().react.get()
    console.log 'getFormData ', Template.instance().react.get()
    return {
      uploadToken: if Meteor.user() and Meteor.user().uploadToken then Meteor.user().uploadToken.token else null
    }
```

On server I have tried to make a user dependent directory:
```coffee 
Fiber = Npm.require 'fibers'

Meteor.startup ->
  UploadServer.init
    tmpDir: process.env.PWD + '/.uploads/tmp'
    uploadDir: process.env.PWD + '/.uploads/'
    checkCreateDirectories: true
    getDirectory: (fileInfo, formData) ->
      dir = ''
      Fiber( ->
        u = Meteor.users.findOne({"uploadToken.token": formData.uploadToken})
        if u
          dir = u.username
      ).run()
      console.log 'dir: ', formData.uploadToken, dir
      return dir
  return
```

The logged formData.uploadTocken is either empty or contains an old token.

Is there a reason because the template upload_bootstrap is not reactive?
Otherwise everything is working fine, include the upload.

**Comment by tomitrescak** [comment]
First, please be respectful of the choice of the programming language. If I use JavaScript and not coffee, it's for a reason. And that reason is that I do not like the Python like syntax. Maybe I'm lame, but I just never learnt to read it or like it. So, if I made the effort to release open source package in one language, you should do the same effort to ask me questions in my langugage.

Second, this is more a Meteor reactivity question, not related to the plugin so you are probably in the wrong place. Please repost to Stack Overflow, maybe they will be a bit less a..holes then me,

But, looking at your example, it does not matter that you use reactive Meteor.User(), if you do not change the user record, the computation will not get executed.
