### ISSUE TITLE
Finished and Fiber

### ISSUE THREAD

**Issue by galdo666** [tomitrescak/meteor-uploads#18]
first off thanks for your work. I try to insert a record in a collection after upload is finished but I get the error "error: meteor code must always run within a fiber". I try to use meteor wrapAsynch function but the Fiber is not active (Fiber.current is undefined). I resolve it to wrap my code in a Fiber(...).run scope, is it the correct way? 

Thanks.

**Comment by tomitrescak** [comment]
Hey, the easiest way is to do it in client, not on server.

**Comment by spikey82** [comment]
I actually do the same because I generate an unique image id based on the upload directly, not causing any more client-server overhead. You can also use the client-side example of tomit that's on GitHub.

Tomit, can't you wrap the callback in a Meteor.bindEnvironment scope? This way, you have access to Meteors scope from within the callback.

**Comment by tomitrescak** [comment]
Souter, am off till mid of January with iPad only. Are you able to do a
small pull request? I would really appreciate it.

Thanks!

Tomas

**Comment by tomitrescak** [comment]
Solved in 398aff32d1c8d9982eef7c9b7cc60e08948268b4 

I used Fibers not MEteor.binEnvironment, which did not work properly. It is now possible to insert data to DB on server
