### ISSUE TITLE
allow or deny serving the /upload/uploaded_file

### ISSUE THREAD

**Issue by daxr** [tomitrescak/meteor-uploads#58]
Great package! 
Im just wondering if there a way to control showing/downloading the uploaded files?

**Comment by tomitrescak** [comment]
Not sure what you mean. You can show files, when you receive the "validate" callback or "finished" callback on client.

**Comment by theduke** [comment]
He wants a way to control ACCESSING the uploaded files.
Some sort of allow callback in UploadServer.serve().

I would need something like this too.

**Comment by tomitrescak** [comment]
I can create a callback but it will not run in Meteor thread since file serving is running in a process of its own :/ User validation will have to be handled in some other manner.

**Comment by webstudiopro** [comment]
Hi,
Having related question. Is it possible (without hacking the package) to add a custom field with the loged in user id, cause Meteor.userId() won't work if its a process of its own when using a method in the finished callback
I need to store the userid with the filename
thx

**Comment by JobJob** [comment]
Ok so there's no current way to restrict access to the uploaded files to a specific Meteor userId (i.e. a logged in user)? So essentially this package is only designed for uploading and serving publicly accessible files?

**Comment by huntonas** [comment]
I did this using the subscription/publications.

**Comment by tomitrescak** [comment]
You can always do validation on client using the `validate` callback. As mentioned earlier, the upload server runs (naturally) not in a meteor process, but in a thread of its own, just like all Iron Router server routes. The implementation of client validation on server has been covered many time on forums. For example you can use shared secrets, tokens ... This is a general use package that handles file upload and serving into/from a server directory, all the rest is up to developer.

**Comment by tomitrescak** [comment]
On top of that, you can always send userID as part of the formData and then use it on server.

**Comment by JobJob** [comment]
Hi @tomitrescak thanks for the fast response. The `validateRequest` callback is only called for uploads at this time correct (hence this issue)? If it were called for GET requests (to /upload/filename.jpg) too, then we could do some validation on accessing the files, but it seems even then we wouldn't have access to the Meteor accounts system so we'd have roll our own user authentication? This is a bridge too far for me personally. I looked on https://forums.meteor.com I couldn't find anything particularly relevant to this case - is that the forums you were referring to? Some way to integrate with Meteor's own authentication seems sensible. At this stage I'm looking into using [CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS) as an alternative, which is a shame because this package seems to have many nice features. Possibly an integration with CollectionFS would make sense.

@huntonas I assume you returned the paths of images appropriate for a particular user? If so someone could still access the uploaded images by e.g. guessing/brute forcing the urls. Can you provide more details?

**Comment by tomitrescak** [comment]
@JobJob I have rolled out a functionality that ALL requests to server are now validated.
As a result, you can now create a hook:

```javascript
//file:/server/init.js
Meteor.startup(function () {
  UploadServer.init({
    ...
    validateRequest: function(req, res) {
      console.log(req.url);
    }
  });
});
```

Now it's only up to you how you will validate this request. If you want to validate user access to specific directory:

1. Create a user token on server (shared secret), remember it on server and pass it onto client
2. Add this token as a part of the file request url
3. Parse URL
4. Compare tokens (now, you will obtain all user info)

You are free to do whatever you want to do.

Not having access on server side routes is ajust the way it is (see [here](http://stackoverflow.com/questions/27714618/server-side-routes-in-iron-router-and-meteor)). I also see it as a performance problem, running instance of server side file serving in a user context.

**Comment by JobJob** [comment]
@tomitrescak Nice work! Cheers. Thanks for the link too!
