### ISSUE TITLE
Crashing in Windows - no such file or directory

### ISSUE THREAD

**Issue by mesosteros** [tomitrescak/meteor-uploads#66]
My project was working and suddenly it started giving out this error. I'm using Meteor for Windows.
I had nailed down the folder locations and it was working perfectly.
        tmpDir: "\..\\..\\..\\..\\..\\.uploads\\tmp\\",
        uploadDir:  "\..\\..\\..\\..\\..\\.uploads\\",
Yet in the error it's pointing to the  'C:\.uploads\tmp' which is obviously not my project location.

Your app is crashing. Here's the latest log.

C:\Users\mesos_000\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
Error: ENOENT, no such file or directory 'C:\.uploads\tmp'
    at Object.fs.mkdirSync (fs.js:654:18)
    at checkCreateDirectory (packages/tomi:upload-server/upload_server.js:454:1)
    at Object.UploadServer.init (packages/tomi:upload-server/upload_server.js:89:1)
    at app\server\init.js:2:18
    at C:\Users\mesos_000\Desktop\Projects\fileUploadsMeteor\.meteor\local\build\programs\server\boot.js:229:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by mesosteros** [comment]
Found the problem... because the package library references /.uploads/.tmp, I also need to have that folder at C:. I had just deleted it because I thought it was unrelated.
Obviously, this is something that needs to be fixed by adapting the package to the windows filesystem quirks.

**Comment by tomitrescak** [comment]
@mesosteros the windows support will come when meteor will announce the official support. They still have not decided how to deal with directories. Or at least not fixed decision has yet come.

**Comment by valisjan** [comment]
Same problem here with Meteor 1.1.0.2 official for Windows. I keep waiting for a fix.
Thank you.

**Comment by tomitrescak** [comment]
I have just tested on windows and all was good. I need a minimally reproducible app to simulate it. please post a zip file here. Thanks.

**Comment by linjinjin123** [comment]
@tomitrescak @mesosteros 
I work in Window 8.1.
When I use meteor-uploads, I got the same problem.
The log is :
W20150501-10:34:13.844(8)? (STDERR)
W20150501-10:34:13.846(8)? (STDERR) events.js:72
W20150501-10:34:13.847(8)? (STDERR)         throw er; // Unhandled 'error' event
W20150501-10:34:13.847(8)? (STDERR)               ^
W20150501-10:34:13.847(8)? (STDERR) Error: ENOENT, open 'C:\Users\linjinjin\Desktop\week8\week8\.meteor\local\build\prog
rams\server\undefined\uploads\tmp\4f1ba4213e54a2bcc9dacbdf25af2da7'

and I try to change some code in the /server/init.js file: 
<code> tmpDir:  '/uploads/tmp' </code>
<code>uploadDir: '/uploads/' </code>

but it still got an error, The log is :
W20150501-10:34:54.515(8)? (STDERR)
W20150501-10:34:54.516(8)? (STDERR) events.js:72
W20150501-10:34:54.516(8)? (STDERR)         throw er; // Unhandled 'error' event
W20150501-10:34:54.516(8)? (STDERR)               ^
W20150501-10:34:54.516(8)? (STDERR) Error: ENOENT, open 'C:\uploads\tmp\05cd9d55b56750b4dd4deb12d0079e69'

The path is wrong. I think '/uploads/tmp' should be 'projectroot/uploads/tmp' so that it could be used easier
So I build a folder : myproject_rootpath/uploads/tmp)
Finally, I slove this problem with these code..
<code>tmpDir: process.cwd() + '/../../../../../uploads/tmp',</code>
<code>uploadDir: process.cwd() + '/../../../../../uploads/',</code>

I think too many ../../../ is a bad method, but it work...And now I can upload a file to server and it's saved in myproject_rootpath/uploads

Hope these help you.
// I am sorry for my English expression skill..

**Comment by tomitrescak** [comment]
how about using environment variables that would store absolute path?

**Comment by sri85** [comment]
@tomitrescak I am able to upload the file in windows but i am not seeing the visual progress bar . Is this is a known issue?

**Comment by tomitrescak** [comment]
No, the windows compatibility has been tested and all worked out fine.

Can this be closed?

**Comment by batjko** [comment]
Guys, I noticed you can use *nix-like paths, for example:

`'/uploads/tmp'` will automagically translate on Windows into `C:\uploads\tmp`.

Works for me.

**Comment by genyded** [comment]
There is an issue here... it is in tomi_upload-server.js in the function below. If it is fed a dir of C:/testdir the output will become /C:/testdir to which on Windows will then get another C: appended because it's perceived the drive letter is missing and you will end up with C:/C:/testdir.

So unless/until this issue is fixed, you can pre-create the directories and brute force them on Windows and they should work, but you CANNOT call checkCreateDirectories because it will fail no matter how you pass the starting dir in. That means if you distribute your app, your customers will need to pre-create the directories as well.

If this gets fixed, dirs can be auto-created on Windows as well. It is not an issue on *nix because the is no drive letter. Using npm fs to join the dirs instead if the srting joins below should allow it to work on all platforms. (https://nodejs.org/docs/latest/api/fs.html)

var checkCreateDirectory = function (dir) {                                                                // 484
  if (!dir) {                                                                                              // 485
    return;                                                                                                // 486
  }                                                                                                        // 487
                                                                                                           // 488
  var dirParts = dir.split('/');                                                                           // 489
  var currentDir = '/';                                                                                    // 490
                                                                                                           // 491
  for (var i = 0; i < dirParts.length; i++) {                                                              // 492
    if (!dirParts[i]) {                                                                                    // 493
      continue;                                                                                            // 494
    }                                                                                                      // 495
                                                                                                           // 496
    currentDir += dirParts[i] + '/';                                                                       // 497
                                                                                                           // 498
    if (!fs.existsSync(currentDir)) {                                                                      // 499
      fs.mkdirSync(currentDir);                                                                            // 500
      console.log('Created directory: ' + currentDir);                                                     // 501
    }                                                                                                      // 502
  }                                                                                                        // 503
}

**Comment by tomitrescak** [comment]
Are you sure you have everything setup correctly? Had no reports on windows problems for a long time. Otherwise, can you Mayer do Paul request please? Am a bit short on time

**Comment by batjko** [comment]
@genyded Did you read my previous comment by any chance?
If you want to use `C:\uploads\tmp`, use this fake-unix path `/uploads/tmp`.
On Windows, the package will translate this into the one you want.

**Comment by genyded** [comment]
I did ... and it can be worked-around, but it's still not a goo idea to glue paths together in a package like this one is. My concern with the work around is that if anything changes moving forward (like this gets fixed), then the app is broken, or at least uploads are. 

It also means you have to have the WHOLE path in the init (since the drive letter is first), so when backing up from cwd() or whatever you need a but load of /../ in the init. Would be nice to just append to the path created elsewhere. 

If I get time, I may fix ti and submit a pull request, but I am really busy right now.

**Comment by onbjerg** [comment]
Doesn't work here either. Please fix it. It works in production (Linux server), but on my development environment which is currently Windows (shiver) it doesn't work.

**Comment by onbjerg** [comment]
For anyone interested in a workaround, you can currently use this piece of code to make it work (the path is from original post):

```js
var path = Npm.require('path')
var dir = path.resolve('..\..\..\..\..\.uploads\tmp\')

if(/^win/.test(process.platform)) {
  dir= dir.replace(/([A-Z]:[\\\/]).*?/gi, '')
}
```

**Comment by tomitrescak** [comment]
Thanks @onbjerg ! Version 1.3.1 of server contains this fix.

**Comment by mellowcello77** [comment]
> Guys, I noticed you can use *nix-like paths, for example:
> 
> `'/uploads/tmp'` will automagically translate on Windows into `C:\uploads\tmp`.
> 
> Works for me.

Thanks this worked, I just created a folder and pointed the directory straight to 'c:/public' on my local server, simple solution to something that started off very complex.
