### ISSUE TITLE
Uploading url of file to collection

### ISSUE THREAD

**Issue by sangyoo91** [tomitrescak/meteor-uploads#73]
This is what I have on my file.

However, the url of the file will not get updated to the collection below.
(image itself gets updated correctly)

Am I doing something wrong?

```
//file:/server/init.js
Meteor.startup(function () {
  UploadServer.init({
    tmpDir: process.env.PWD + '/.uploads/tmp',
    uploadDir: process.env.PWD + '/.uploads/',
    checkCreateDirectories: true,
    getDirectory: function(fileInfo, formData) {
      if (formData && formData.directoryName != null) {
        return formData.directoryName;
      }
      return "";
    },
    getFileName: function(fileInfo, formData) {
      if (formData && formData.prefix != null) {
        return formData.prefix + '_' + fileInfo.name;
      }
      return fileInfo.name;
    },
    finished: function(fileInfo, formData) {
      if (formData && formData._id != null) {
        Meteor.users.update(this.userId, { $set: { "profile.avatar":fileInfo }});
      }
    }
  })
  Uploader.finished = function(index, file) {
    Meteor.users.update(this.userId, { $set: { "profile.avatar":file }});
  }
});
```

**Comment by tomitrescak** [comment]
Several things, first, on server the this.userId is not defined so following will do nothing:

```
finished: function(fileInfo, formData) {
      if (formData && formData._id != null) {
        Meteor.users.update(this.userId, { $set: { "profile.avatar":fileInfo }});
      }
    }
```

You may want to pass userId as part of formData.

On client, make sure that client modifications are permitted.

**Comment by sangyoo91** [comment]
Ah, I'm a really big newb and I will try to write something up. Where does fileInfo and formData come from?

**Comment by sangyoo91** [comment]
```
{{>upload__bootstrap formData=specificFormData}} 
```

How would I pass the userId to that specificFormData?

```
Template.foo.helpers({
  specificFormData : function(){
    return Meteor.userId()
  }
```

Would this be the correct way?

**Comment by foxaal** [comment]
Yes, that looks close to right except for some typos and I think you need to return an object.  In closed issue #53 I put some code in there which may help with the forms data.  In your code above, you may have to put the return value in an object, something like: return { userId : Meteor . userId ( ) } ;

**Comment by sangyoo91** [comment]
@foxaal Hello. Thank you for your reply. I saw your link and did not quite understand it.
```
//file:/server/init.js
Meteor.startup(function () {
  UploadServer.init({
    tmpDir: process.env.PWD + '/.uploads/tmp',
    uploadDir: process.env.PWD + '/.uploads/',
    checkCreateDirectories: true,
    // maxFileSize: 100000,
    getDirectory: function(fileInfo, formData) {
      if (formData && formData.directoryName != null) {
        return formData.directoryName;
      }
      return "";
    },
    getFileName: function(fileInfo, formData) {
      if (formData && formData.prefix != null) {
        return formData.prefix + '_' + fileInfo.name;
      }
      return fileInfo.name;
    },
    finished: function(fileInfo, formData) {
      if (formData && formData._id != null) {
	        Meteor.users.update({_id:formData.userId}, { $set: { "profile.avatar":fileInfo }});
      }
    }
  })
});
```

This is what I have on my server side.

And this is what I have on my client
```
Template.postsList.helpers({
	specificFormData: function(){
		return { userId: Meteor.userId() };
	}
});
```

the url is not being updated to the users :(

**Comment by foxaal** [comment]
I apologize if I cannot see exactly what you are trying to do, but it seems you may need a bit of help untangling how this works.  So do I, because a lot goes on automagically. although, perhaps less magically than one may think.  For me, always best to start looking at this from the templates and work down from there.  Somewhere in the html, you have must have:
```<template name="postsList">
{{> upload_bootstrap formData=specificFormData ..... }}
</template>
```
Your helper function, `specificFormData` will be called when the upload_bootstrap template renders, and by this mechanism, the upload_bootstrap template will receive the return value of `specificFormData`, namely, an object which has a `userId` property.  This object gets a name at this point called `formData`.  The `getDirectory` function which you fill in for the UploadServer is called with  `formData` -- which, from the code you have shown here, does not contain a `directoryName` property (or a `prefix` property, or an `_id` property) but only a `userId` property.  `getDirectory` will tell the UploadServer the name of a sub-directory to upload to.  In this case, that name will be the value of `userId` property of `formData`.

**Comment by tomitrescak** [comment]
Did you solve it? Can I close this issue?

**Comment by sangyoo91** [comment]
@tomitrescak Yes I solved it! I do not understand yet fully how this package handles data but this issue has been solved. Thank you
